=- name: change repo 
  shell: rpm -Uvh https://mirrors.aliyun.com/zabbix/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
  shell: sed -i 's@http://repo.zabbix.com@https://mirrors.aliyun.com/zabbix@' /etc/yum.repos.d/zabbix.repo
  shell: yum clean all

- name: install zabbix-server-mysql zabbix-agent
  yum: name=zabbix-server-mysql tate=present

- name: install Software Collections
  yum: name=centos-release-scl tate=present

- name: install mariadb
  yum: name=