- name: config zabbix repo from aliyun
  copy: src=zabbix.repo dest=/etc/yum.repos.d/

- name: yum clean
  shell: yum clean all

- name: install zabbix-server-mysql
  yum: name=zabbix-server-mysql state=present

- name: install Software Collections
  yum: name=centos-release-scl state=present

- name: install mariadb
  yum: name=mariadb-server state=present