- name: download tomcat8
  get_url: url=http://pan.ecarry.cc/software/apache-tomcat-8.5.63.tar.gz dest=/usr/local/

- name: unzip tomcat
  shell: tar -zxf /usr/local/apache-tomcat-8.5.63.tar.gz

- name: create symbolic link
  shell: ln -s /usr/local/apache-tomcat-8.5.63 /usr/local/tomcat

- name: set $CATALINA
  copy: src=tomcat.sh dest=/etc/profile.d/

- name: tomcat.sh
  shell: . /etc/profile.d/tomcat.sh